EAG4-20 = Added logic to fetch all players count
MykhailoHoroshko/who-am-i-game-frontend pull request #19
Opened 2022-06-23 14:11 UTC by Gredgit

2022-06-23 14:46 UTC, MykhailoHoroshko requested changes

2022-06-23 14:46 UTC, MykhailoHoroshko commented on src/screens/home/home.jsx
> +    setPlayerNum(await (await getAllPlayersCount(playerId)).data);
first await is redundant

2022-06-23 14:46 UTC, MykhailoHoroshko commented on src/screens/home/home.jsx
> +export const useInterval = (callback, delay) => {
create `/src/hooks/useInterval.js` file and move there

2022-06-23 14:46 UTC, MykhailoHoroshko commented on src/screens/home/home.jsx
> +      savedCallback.current();
check if `savedCallback.current !== null` or initialize ref with empty function

2022-06-23 14:48 UTC, MykhailoHoroshko commented on src/screens/home/home.jsx
> +    savedCallback.current = callback;
add check if callback is function

2022-06-23 15:24 UTC, Gredgit commented on src/screens/home/home.jsx
> +    savedCallback.current = callback;
fixed

2022-06-23 17:04 UTC, MykhailoHoroshko commented on src/hooks/useInterval.js
> +export const useInterval = (callback, delay) => {
Change to default export

2022-06-24 03:58 UTC, MykhailoHoroshko approved these changes

2022-06-24 03:58 UTC, merged